# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33ee2458c7d87ace65c74bc90c199464842746867210a5c3791729b29fa8bb2f091424d64b3de63cc1acd323f0ada4f8464f7fd72bde7c10f057555f25434ac

test:
  secret_key_base: 07ceebc7489fbb19cd9ac67632e114d05113824f4201139fa4b04dc614c8b87c18b5ce802976f57df5192f4feff162b375b29203aad7794605785cb266527a23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
